// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Website, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeleteSession(ctx context.Context, tokenHash string) error
	GetSessionUser(ctx context.Context, arg GetSessionUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetWebsite(ctx context.Context, id string) (Website, error)
	ListWebsites(ctx context.Context) ([]Website, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
