// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: websites.sql

package db

import (
	"context"
)

const createWebsite = `-- name: CreateWebsite :one
INSERT INTO websites (id, name, domain, timezone, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, domain, timezone, created_at
`

type CreateWebsiteParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Domain    string `json:"domain"`
	Timezone  string `json:"timezone"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Website, error) {
	row := q.db.QueryRowContext(ctx, createWebsite,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Timezone,
		arg.CreatedAt,
	)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getWebsite = `-- name: GetWebsite :one
SELECT id, name, domain, timezone, created_at FROM websites WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebsite(ctx context.Context, id string) (Website, error) {
	row := q.db.QueryRowContext(ctx, getWebsite, id)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const listWebsites = `-- name: ListWebsites :many
SELECT id, name, domain, timezone, created_at FROM websites ORDER BY created_at ASC
`

func (q *Queries) ListWebsites(ctx context.Context) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listWebsites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Website{}
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
